version: '3.8'

services:
  tournament-app:
    build: .
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Optional: für persistente Daten
    networks:
      - tournament-network

networks:
  tournament-network:
    driver: bridge