version: '3.8'

services:
  tournament-app:
    build: .
    ports:
      - "${PORT:-5678}:${PORT:-5678}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5678}
    restart: unless-stopped
    volumes:
      # Persistente Datenspeicherung
      - ./saves:/app/saves
      # Live Code Updates (für Entwicklung)
      - ./public:/app/public
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      # Node modules bleiben im Container
      - /app/node_modules
    networks:
      - tournament-network
    # Für Live-Reload
    command: npm run dev

networks:
  tournament-network:
    driver: bridge